/// Module for serving bundled KaTeX assets (CSS, JS, fonts)

pub const CSS: &[u8] = include_bytes!("../assets/katex/katex.min.css");
pub const JS: &[u8] = include_bytes!("../assets/katex/katex.min.js");

pub fn get_font(name: &str) -> Option<(&'static [u8], &'static str)> {
    let (data, mime): (&[u8], &str) = match name {
        "KaTeX_AMS-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_AMS-Regular.woff2"), "font/woff2"),
        "KaTeX_AMS-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_AMS-Regular.woff"), "font/woff"),
        "KaTeX_AMS-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_AMS-Regular.ttf"), "font/ttf"),
        "KaTeX_Caligraphic-Bold.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Caligraphic-Bold.woff2"), "font/woff2"),
        "KaTeX_Caligraphic-Bold.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Caligraphic-Bold.woff"), "font/woff"),
        "KaTeX_Caligraphic-Bold.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Caligraphic-Bold.ttf"), "font/ttf"),
        "KaTeX_Caligraphic-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Caligraphic-Regular.woff2"), "font/woff2"),
        "KaTeX_Caligraphic-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Caligraphic-Regular.woff"), "font/woff"),
        "KaTeX_Caligraphic-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Caligraphic-Regular.ttf"), "font/ttf"),
        "KaTeX_Fraktur-Bold.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Fraktur-Bold.woff2"), "font/woff2"),
        "KaTeX_Fraktur-Bold.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Fraktur-Bold.woff"), "font/woff"),
        "KaTeX_Fraktur-Bold.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Fraktur-Bold.ttf"), "font/ttf"),
        "KaTeX_Fraktur-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Fraktur-Regular.woff2"), "font/woff2"),
        "KaTeX_Fraktur-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Fraktur-Regular.woff"), "font/woff"),
        "KaTeX_Fraktur-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Fraktur-Regular.ttf"), "font/ttf"),
        "KaTeX_Main-Bold.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-Bold.woff2"), "font/woff2"),
        "KaTeX_Main-Bold.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-Bold.woff"), "font/woff"),
        "KaTeX_Main-Bold.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-Bold.ttf"), "font/ttf"),
        "KaTeX_Main-BoldItalic.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-BoldItalic.woff2"), "font/woff2"),
        "KaTeX_Main-BoldItalic.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-BoldItalic.woff"), "font/woff"),
        "KaTeX_Main-BoldItalic.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-BoldItalic.ttf"), "font/ttf"),
        "KaTeX_Main-Italic.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-Italic.woff2"), "font/woff2"),
        "KaTeX_Main-Italic.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-Italic.woff"), "font/woff"),
        "KaTeX_Main-Italic.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-Italic.ttf"), "font/ttf"),
        "KaTeX_Main-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-Regular.woff2"), "font/woff2"),
        "KaTeX_Main-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-Regular.woff"), "font/woff"),
        "KaTeX_Main-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Main-Regular.ttf"), "font/ttf"),
        "KaTeX_Math-BoldItalic.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Math-BoldItalic.woff2"), "font/woff2"),
        "KaTeX_Math-BoldItalic.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Math-BoldItalic.woff"), "font/woff"),
        "KaTeX_Math-BoldItalic.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Math-BoldItalic.ttf"), "font/ttf"),
        "KaTeX_Math-Italic.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Math-Italic.woff2"), "font/woff2"),
        "KaTeX_Math-Italic.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Math-Italic.woff"), "font/woff"),
        "KaTeX_Math-Italic.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Math-Italic.ttf"), "font/ttf"),
        "KaTeX_SansSerif-Bold.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_SansSerif-Bold.woff2"), "font/woff2"),
        "KaTeX_SansSerif-Bold.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_SansSerif-Bold.woff"), "font/woff"),
        "KaTeX_SansSerif-Bold.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_SansSerif-Bold.ttf"), "font/ttf"),
        "KaTeX_SansSerif-Italic.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_SansSerif-Italic.woff2"), "font/woff2"),
        "KaTeX_SansSerif-Italic.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_SansSerif-Italic.woff"), "font/woff"),
        "KaTeX_SansSerif-Italic.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_SansSerif-Italic.ttf"), "font/ttf"),
        "KaTeX_SansSerif-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_SansSerif-Regular.woff2"), "font/woff2"),
        "KaTeX_SansSerif-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_SansSerif-Regular.woff"), "font/woff"),
        "KaTeX_SansSerif-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_SansSerif-Regular.ttf"), "font/ttf"),
        "KaTeX_Script-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Script-Regular.woff2"), "font/woff2"),
        "KaTeX_Script-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Script-Regular.woff"), "font/woff"),
        "KaTeX_Script-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Script-Regular.ttf"), "font/ttf"),
        "KaTeX_Size1-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Size1-Regular.woff2"), "font/woff2"),
        "KaTeX_Size1-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Size1-Regular.woff"), "font/woff"),
        "KaTeX_Size1-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Size1-Regular.ttf"), "font/ttf"),
        "KaTeX_Size2-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Size2-Regular.woff2"), "font/woff2"),
        "KaTeX_Size2-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Size2-Regular.woff"), "font/woff"),
        "KaTeX_Size2-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Size2-Regular.ttf"), "font/ttf"),
        "KaTeX_Size3-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Size3-Regular.woff2"), "font/woff2"),
        "KaTeX_Size3-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Size3-Regular.woff"), "font/woff"),
        "KaTeX_Size3-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Size3-Regular.ttf"), "font/ttf"),
        "KaTeX_Size4-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Size4-Regular.woff2"), "font/woff2"),
        "KaTeX_Size4-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Size4-Regular.woff"), "font/woff"),
        "KaTeX_Size4-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Size4-Regular.ttf"), "font/ttf"),
        "KaTeX_Typewriter-Regular.woff2" => (include_bytes!("../assets/katex/fonts/KaTeX_Typewriter-Regular.woff2"), "font/woff2"),
        "KaTeX_Typewriter-Regular.woff" => (include_bytes!("../assets/katex/fonts/KaTeX_Typewriter-Regular.woff"), "font/woff"),
        "KaTeX_Typewriter-Regular.ttf" => (include_bytes!("../assets/katex/fonts/KaTeX_Typewriter-Regular.ttf"), "font/ttf"),
        _ => return None,
    };
    Some((data, mime))
}
